version: '3'
services:
  db:
    build: ./database
    image: dev-db
    restart: always
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rpass
    ports:
      - 3306:3306
    container_name: accretion-container
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d